### ISSUE TITLE
加载这个页面直接闪退是什么原因呢

### ISSUE THREAD

**Issue by AngoLGW** [flyskywhy/react-native-gcanvas#10]

**Comment by flyskywhy** [comment]
给个 logcat 以便我分析下？

**Comment by liuhuapiaoyuan** [comment]
I/CANVAS: GCanvasJNI init from StaticBlock
E/CANVAS: gcanvas is not found.dlopen failed: library "libfreetype.so" not found
I/CANVAS: GCanvasJNI init end---- 
    GCanvasJNI init from load()
E/CANVAS: gcanvas is not found.dlopen failed: library "libfreetype.so" not found
I/CANVAS: GCanvasJNI init end---- 
E/oud.suntree.em: No implementation found for void com.taobao.gcanvas.GCanvasJNI.setContextType(java.lang.String, int) (tried Java_com_taobao_gcanvas_GCanvasJNI_setContextType and Java_com_taobao_gcanvas_GCanvasJNI_setContextType__Ljava_lang_String_2I)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cloud.suntree.ems, PID: 7144
    java.lang.UnsatisfiedLinkError: No implementation found for void com.taobao.gcanvas.GCanvasJNI.setContextType(java.lang.String, int) (tried Java_com_taobao_gcanvas_GCanvasJNI_setContextType and Java_com_taobao_gcanvas_GCanvasJNI_setContextType__Ljava_lang_String_2I)
        at com.taobao.gcanvas.GCanvasJNI.setContextType(Native Method)
        at com.taobao.gcanvas.GCanvasJNI.setWrapperContextType(GCanvasJNI.java:263)
        at com.taobao.gcanvas.surface.GTextureViewCallback.<init>(GTextureViewCallback.java:49)
        at com.taobao.gcanvas.surface.GTextureView.init(GTextureView.java:70)
        at com.taobao.gcanvas.surface.GTextureView.<init>(GTextureView.java:21)
        at com.taobao.gcanvas.bridges.rn.GReactTextureView.<init>(GReactTextureView.java:27)
        at com.taobao.gcanvas.bridges.rn.GReactViewManager.createViewInstance(GReactViewManager.java:28)
        at com.taobao.gcanvas.bridges.rn.GReactViewManager.createViewInstance(GReactViewManager.java:18)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1103)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1074)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by liuhuapiaoyuan** [comment]
> @liuhuapiaoyuan ，从没有找到 libfreetype.so 来看，我觉得你是否在非 arm 平台（比如那些号称运行速度飞快的模拟器其实是模拟了 x86 平台）上运行？原始阿里官方的 GCanvas 的 react-native 版本就只支持 "armeabi-v7a" 和 "arm64-v8a" 这两个 ABI 的，所以请直接在手机上运行看看？

我是用android studio的模拟器，嗯 我试试直接安卓机
